--
-- PostgreSQL database dump
--

-- Dumped from database version 16.0
-- Dumped by pg_dump version 16.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pg_stat_statements; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_stat_statements WITH SCHEMA public;


--
-- Name: EXTENSION pg_stat_statements; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_stat_statements IS 'track planning and execution statistics of all SQL statements executed';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ar_internal_metadata; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ar_internal_metadata (
    key character varying NOT NULL,
    value character varying,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: good_job_batches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.good_job_batches (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    description text,
    serialized_properties jsonb,
    on_finish text,
    on_success text,
    on_discard text,
    callback_queue_name text,
    callback_priority integer,
    enqueued_at timestamp without time zone,
    discarded_at timestamp without time zone,
    finished_at timestamp without time zone
);


--
-- Name: good_job_executions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.good_job_executions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    active_job_id uuid NOT NULL,
    job_class text,
    queue_name text,
    serialized_params jsonb,
    scheduled_at timestamp without time zone,
    finished_at timestamp without time zone,
    error text,
    error_event integer
);


--
-- Name: good_job_processes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.good_job_processes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    state jsonb
);


--
-- Name: good_job_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.good_job_settings (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    key text,
    value jsonb
);


--
-- Name: good_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.good_jobs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    queue_name text,
    priority integer,
    serialized_params jsonb,
    scheduled_at timestamp without time zone,
    performed_at timestamp without time zone,
    finished_at timestamp without time zone,
    error text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    active_job_id uuid,
    concurrency_key text,
    cron_key text,
    retried_good_job_id uuid,
    cron_at timestamp without time zone,
    batch_id uuid,
    batch_callback_id uuid,
    is_discrete boolean,
    executions_count integer,
    job_class text,
    error_event integer
);


--
-- Name: iscn; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.iscn (
    id bigint NOT NULL,
    iscn_id text,
    iscn_id_prefix text,
    version text,
    owner text,
    name text,
    description text,
    url text,
    keywords text[],
    content_fingerprints text[],
    ipld text,
    data jsonb
);


--
-- Name: iscn_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.iscn ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.iscn_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: nft_classes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nft_classes (
    id bigint NOT NULL,
    class_id text NOT NULL,
    parent_type text,
    parent_iscn_id_prefix text,
    parent_iscn_version_at_mint text,
    parent_account text,
    name text,
    symbol text,
    description text,
    uri text,
    uri_hash text,
    metadata jsonb,
    config jsonb,
    class_created_at timestamp without time zone
);


--
-- Name: nft_classes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.nft_classes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nft_classes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: nfts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nfts (
    id bigint NOT NULL,
    class_id text,
    nft_id text,
    uri text,
    uri_hash text,
    owner text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: nfts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.nfts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nfts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    filename text NOT NULL
);


--
-- Name: ar_internal_metadata ar_internal_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ar_internal_metadata
    ADD CONSTRAINT ar_internal_metadata_pkey PRIMARY KEY (key);


--
-- Name: good_job_batches good_job_batches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.good_job_batches
    ADD CONSTRAINT good_job_batches_pkey PRIMARY KEY (id);


--
-- Name: good_job_executions good_job_executions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.good_job_executions
    ADD CONSTRAINT good_job_executions_pkey PRIMARY KEY (id);


--
-- Name: good_job_processes good_job_processes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.good_job_processes
    ADD CONSTRAINT good_job_processes_pkey PRIMARY KEY (id);


--
-- Name: good_job_settings good_job_settings_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.good_job_settings
    ADD CONSTRAINT good_job_settings_key_key UNIQUE (key);


--
-- Name: good_job_settings good_job_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.good_job_settings
    ADD CONSTRAINT good_job_settings_pkey PRIMARY KEY (id);


--
-- Name: good_jobs good_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.good_jobs
    ADD CONSTRAINT good_jobs_pkey PRIMARY KEY (id);


--
-- Name: iscn iscn_iscn_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.iscn
    ADD CONSTRAINT iscn_iscn_id_key UNIQUE (iscn_id);


--
-- Name: iscn iscn_iscn_id_prefix_version_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.iscn
    ADD CONSTRAINT iscn_iscn_id_prefix_version_key UNIQUE (iscn_id_prefix, version);


--
-- Name: iscn iscn_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.iscn
    ADD CONSTRAINT iscn_pkey PRIMARY KEY (id);


--
-- Name: nft_classes nft_classes_class_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nft_classes
    ADD CONSTRAINT nft_classes_class_id_key UNIQUE (class_id);


--
-- Name: nft_classes nft_classes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nft_classes
    ADD CONSTRAINT nft_classes_pkey PRIMARY KEY (id);


--
-- Name: nfts nfts_class_id_nft_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nfts
    ADD CONSTRAINT nfts_class_id_nft_id_key UNIQUE (class_id, nft_id);


--
-- Name: nfts nfts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nfts
    ADD CONSTRAINT nfts_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (filename);


--
-- Name: good_jobs_batch_callback_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX good_jobs_batch_callback_id_index ON public.good_jobs USING btree (batch_callback_id) WHERE (batch_callback_id IS NOT NULL);


--
-- Name: good_jobs_batch_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX good_jobs_batch_id_index ON public.good_jobs USING btree (batch_id) WHERE (batch_id IS NOT NULL);


--
-- Name: index_good_job_executions_on_active_job_id_and_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_good_job_executions_on_active_job_id_and_created_at ON public.good_job_executions USING btree (active_job_id, created_at);


--
-- Name: index_good_jobs_jobs_on_finished_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_good_jobs_jobs_on_finished_at ON public.good_jobs USING btree (finished_at) WHERE ((retried_good_job_id IS NULL) AND (finished_at IS NOT NULL));


--
-- Name: index_good_jobs_jobs_on_priority_created_at_when_unfinished; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_good_jobs_jobs_on_priority_created_at_when_unfinished ON public.good_jobs USING btree (priority, created_at) WHERE (finished_at IS NULL);


--
-- Name: index_good_jobs_on_active_job_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_good_jobs_on_active_job_id ON public.good_jobs USING btree (active_job_id);


--
-- Name: index_good_jobs_on_active_job_id_and_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_good_jobs_on_active_job_id_and_created_at ON public.good_jobs USING btree (active_job_id, created_at);


--
-- Name: index_good_jobs_on_concurrency_key_when_unfinished; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_good_jobs_on_concurrency_key_when_unfinished ON public.good_jobs USING btree (concurrency_key) WHERE (finished_at IS NULL);


--
-- Name: index_good_jobs_on_cron_key_and_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_good_jobs_on_cron_key_and_created_at ON public.good_jobs USING btree (cron_key, created_at);


--
-- Name: index_good_jobs_on_cron_key_and_cron_at; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_good_jobs_on_cron_key_and_cron_at ON public.good_jobs USING btree (cron_key, cron_at);


--
-- Name: index_good_jobs_on_queue_name_and_scheduled_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_good_jobs_on_queue_name_and_scheduled_at ON public.good_jobs USING btree (queue_name, scheduled_at) WHERE (finished_at IS NULL);


--
-- Name: index_good_jobs_on_scheduled_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_good_jobs_on_scheduled_at ON public.good_jobs USING btree (scheduled_at) WHERE (finished_at IS NULL);


--
-- Name: iscn_content_fingerprints_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX iscn_content_fingerprints_index ON public.iscn USING gin (content_fingerprints);


--
-- Name: iscn_iscn_id_prefix_version_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX iscn_iscn_id_prefix_version_index ON public.iscn USING btree (iscn_id_prefix, version);


--
-- Name: iscn_keywords_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX iscn_keywords_index ON public.iscn USING gin (keywords);


--
-- Name: iscn_owner_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX iscn_owner_index ON public.iscn USING btree (owner);


--
-- Name: nft_classes_class_created_at_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX nft_classes_class_created_at_index ON public.nft_classes USING btree (class_created_at) WHERE (class_created_at IS NOT NULL);


--
-- Name: nft_classes_class_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX nft_classes_class_id_index ON public.nft_classes USING btree (class_id);


--
-- Name: nft_classes_parent_iscn_id_prefix_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX nft_classes_parent_iscn_id_prefix_index ON public.nft_classes USING btree (parent_iscn_id_prefix);


--
-- Name: nfts_class_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX nfts_class_id_index ON public.nfts USING btree (class_id);


--
-- Name: nfts_created_at_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX nfts_created_at_index ON public.nfts USING btree (created_at);


--
-- Name: nfts_owner_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX nfts_owner_index ON public.nfts USING btree (owner);


--
-- Name: nfts_updated_at_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX nfts_updated_at_index ON public.nfts USING btree (updated_at);


--
-- PostgreSQL database dump complete
--

SET search_path TO "$user", public;
INSERT INTO "schema_migrations" ("filename") VALUES ('20231017090127_create_initial_data_structure.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20231101063614_create_iscn.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20231102020525_create_nfts.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20231103102518_create_good_jobs.rb');